# Generated by Django 5.2.8 on 2025-12-09 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Detection Time')),
                ('anomaly_type', models.CharField(max_length=100, verbose_name='Anomaly Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Severity Level')),
                ('model_confidence', models.FloatField(default=0.0, help_text='Confidence score from ML model (0–1)', verbose_name='Model Confidence')),
            ],
            options={
                'verbose_name': 'Anomaly Event',
                'verbose_name_plural': 'Anomaly Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Generation Time')),
                ('recommended_action', models.TextField(verbose_name='Recommended Action')),
                ('explanation_text', models.TextField(verbose_name='Explanation')),
                ('confidence', models.FloatField(default=0.8, help_text='AI confidence in recommendation (0–1)', verbose_name='Confidence Score')),
                ('anomaly_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='monitoring.anomalyevent', verbose_name='Anomaly Event')),
            ],
            options={
                'verbose_name': 'Agent Recommendation',
                'verbose_name_plural': 'Agent Recommendations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('size', models.FloatField(help_text='Farm size in hectares', verbose_name='Size (ha)')),
                ('crop_type', models.CharField(max_length=100, verbose_name='Crop Type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
                'ordering': ['owner_id', 'location'],
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.CharField(max_length=100, verbose_name='Crop Variety')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='monitoring.farmprofile', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Field Plot',
                'verbose_name_plural': 'Field Plots',
                'ordering': ['farm_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.fieldplot', verbose_name='Field Plot'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil Moisture'), ('temperature', 'Air Temperature'), ('humidity', 'Air Humidity')], max_length=20, verbose_name='Sensor Type')),
                ('value', models.FloatField(verbose_name='Value')),
                ('source', models.CharField(default='simulator', help_text='Source of the data', max_length=50, verbose_name='Data Source')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='monitoring.fieldplot', verbose_name='Field Plot')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
